name: CI with Caching

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Cache dependencies
        id: cache-deps
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            venv
          key: cache-08678cc-${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            cache-08678cc-${{ runner.os }}-pip-
      
      - name: prime-cache-08678cc
        run: |
          echo "Cache hit: ${{ steps.cache-deps.outputs.cache-hit }}"
          if [ "${{ steps.cache-deps.outputs.cache-hit }}" == "true" ]; then
            echo "✓ Cache was restored successfully!"
          else
            echo "✗ Cache miss - dependencies will be installed fresh"
          fi
      
      - name: Create virtual environment
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
      
      - name: Install dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: |
          source venv/bin/activate
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install requests flask pytest
          fi
      
      - name: Display installed packages
        run: |
          if [ -d "venv" ]; then
            source venv/bin/activate
          fi
          pip list
      
      - name: Run tests (demo)
        run: |
          echo "Running tests..."
          echo "All tests passed!"
